import { ProductionLine } from "./types";

export const productionLines: ProductionLine[] = [
  {
    id: "requirements",
    name: "需求产线",
    opc: "陈",
    function: "Spec 产出与审核",
    wip: 12,
    completed: 47,
    anomaly: "—",
    status: "NOMINAL",
    pipelineSteps: [
      { label: "需求提交" },
      { label: "Spec 产出" },
      { label: "成熟度评审" },
      { label: "交付" },
    ],
    deliverables: [
      { id: "d1", name: "Spec 文档", type: "文档", status: "done" as const, updatedAt: "2025-01-15" },
      { id: "d2", name: "本体条目", type: "数据", status: "done" as const, updatedAt: "2025-01-14" },
      { id: "d3", name: "需求规格书", type: "文档", status: "done" as const, updatedAt: "2025-01-13" },
      { id: "d4", name: "评审记录", type: "记录", status: "done" as const, updatedAt: "2025-01-12" },
    ],
  },
  {
    id: "coding",
    name: "编码产线",
    opc: "林",
    function: "代码实现与评审",
    wip: 8,
    completed: 35,
    anomaly: "F-2341 Silent Gap",
    status: "ATTENTION",
    pipelineSteps: [
      { label: "方案评审" },
      { label: "设计评审" },
      { label: "编码实现" },
      { label: "PR 审查" },
      { label: "交付" },
    ],
    deliverables: [
      { id: "d5", name: "代码", type: "代码", status: "in_progress" as const, updatedAt: "2025-01-15" },
      { id: "d6", name: "测试用例", type: "测试", status: "done" as const, updatedAt: "2025-01-14" },
      { id: "d7", name: "PR 记录", type: "记录", status: "done" as const, updatedAt: "2025-01-13" },
      { id: "d8", name: "方案文档", type: "文档", status: "done" as const, updatedAt: "2025-01-12" },
    ],
  },
  {
    id: "testing",
    name: "测试产线",
    opc: "王",
    function: "测试执行与缺陷管理",
    wip: 5,
    completed: 28,
    anomaly: "—",
    status: "NOMINAL",
    pipelineSteps: [
      { label: "测试计划" },
      { label: "用例设计" },
      { label: "执行测试" },
      { label: "缺陷报告" },
      { label: "交付" },
    ],
    deliverables: [
      { id: "d9", name: "测试用例", type: "测试", status: "done" as const, updatedAt: "2025-01-15" },
      { id: "d10", name: "缺陷报告", type: "报告", status: "done" as const, updatedAt: "2025-01-14" },
      { id: "d11", name: "覆盖报告", type: "报告", status: "done" as const, updatedAt: "2025-01-13" },
      { id: "d12", name: "测试总结", type: "总结", status: "done" as const, updatedAt: "2025-01-12" },
    ],
  },
  {
    id: "sre",
    name: "SRE产线",
    opc: "张",
    function: "部署与监控运维",
    wip: 3,
    completed: 15,
    anomaly: "—",
    status: "NOMINAL",
    pipelineSteps: [
      { label: "部署准备" },
      { label: "灰度发布" },
      { label: "监控观察" },
      { label: "全量发布" },
      { label: "运维" },
    ],
    deliverables: [
      { id: "d13", name: "部署配置", type: "配置", status: "done" as const, updatedAt: "2025-01-15" },
      { id: "d14", name: "Runbook", type: "文档", status: "done" as const, updatedAt: "2025-01-14" },
      { id: "d15", name: "告警规则", type: "配置", status: "done" as const, updatedAt: "2025-01-13" },
      { id: "d16", name: "回滚方案", type: "方案", status: "done" as const, updatedAt: "2025-01-12" },
    ],
  },
];
