import type {
  AlertRule,
  Incident,
  LogEntry,
  MetricSnapshot,
  RollbackRecord,
  TraceSpan,
} from "@/types/factory";

// ── Observability: Metrics (4 cards) ──────────────────────────────────

export const sampleMetrics: MetricSnapshot[] = [
  {
    id: "m-err-rate",
    label: "Error Rate",
    value: 0.12,
    unit: "%",
    trend: "up",
    trendValue: 0.03,
    icon: "AlertTriangle",
    subtitle: "5m window",
  },
  {
    id: "m-p99",
    label: "P99 Latency",
    value: 247,
    unit: "ms",
    trend: "down",
    trendValue: 18,
    icon: "Clock",
    subtitle: "vs last hour",
  },
  {
    id: "m-throughput",
    label: "Throughput",
    value: 3840,
    unit: "rps",
    trend: "up",
    trendValue: 120,
    icon: "Zap",
    subtitle: "current",
  },
  {
    id: "m-availability",
    label: "Availability",
    value: 99.97,
    unit: "%",
    trend: "stable",
    trendValue: 0,
    icon: "Shield",
    subtitle: "30-day rolling",
  },
];

// ── Observability: Logs (12 entries) ──────────────────────────────────

export const sampleLogs: LogEntry[] = [
  {
    id: "log-01",
    timestamp: "2026-05-10T14:32:01Z",
    level: "ERROR",
    service: "payment-gateway",
    message: "Timeout connecting to upstream payment processor (attempt 3/3)",
  },
  {
    id: "log-02",
    timestamp: "2026-05-10T14:31:58Z",
    level: "ERROR",
    service: "order-service",
    message: "Database connection pool exhausted (active=120, max=120)",
  },
  {
    id: "log-03",
    timestamp: "2026-05-10T14:31:45Z",
    level: "WARN",
    service: "notification-service",
    message: "APNs push delivery delayed — queue depth > 5000",
  },
  {
    id: "log-04",
    timestamp: "2026-05-10T14:31:30Z",
    level: "WARN",
    service: "order-service",
    message: "Slow query detected (duration=3.2s): SELECT * FROM orders WHERE status = 'pending'",
  },
  {
    id: "log-05",
    timestamp: "2026-05-10T14:31:15Z",
    level: "ERROR",
    service: "payment-gateway",
    message: "SSL certificate verification failed for partner-api.example.com",
  },
  {
    id: "log-06",
    timestamp: "2026-05-10T14:31:00Z",
    level: "INFO",
    service: "order-service",
    message: "Order batch processing completed: 1423 orders in 2.8s",
  },
  {
    id: "log-07",
    timestamp: "2026-05-10T14:30:45Z",
    level: "INFO",
    service: "notification-service",
    message: "Push notification sent successfully to 856 devices",
  },
  {
    id: "log-08",
    timestamp: "2026-05-10T14:30:30Z",
    level: "WARN",
    service: "payment-gateway",
    message: "Retry rate increased to 2.4% (threshold: 1.0%)",
  },
  {
    id: "log-09",
    timestamp: "2026-05-10T14:30:15Z",
    level: "INFO",
    service: "order-service",
    message: "Kafka consumer group rebalancing completed (partition=0-7)",
  },
  {
    id: "log-10",
    timestamp: "2026-05-10T14:30:00Z",
    level: "WARN",
    service: "notification-service",
    message: "FCM endpoint returned 429 — rate limited",
  },
  {
    id: "log-11",
    timestamp: "2026-05-10T14:29:45Z",
    level: "INFO",
    service: "payment-gateway",
    message: "Circuit breaker reset — upstream payment processor recovered",
  },
  {
    id: "log-12",
    timestamp: "2026-05-10T14:29:30Z",
    level: "INFO",
    service: "order-service",
    message: "Health check passed: all dependencies responding",
  },
];

// ── Observability: Traces (8 spans) ───────────────────────────────────

export const sampleTraces: TraceSpan[] = [
  {
    id: "trace-01",
    traceId: "abc123def456",
    service: "payment-gateway",
    operation: "POST /charge",
    duration: 1247,
    status: "error",
  },
  {
    id: "trace-02",
    traceId: "abc123def456",
    service: "payment-processor",
    operation: "ChargeRequest",
    duration: 1020,
    status: "error",
  },
  {
    id: "trace-03",
    traceId: "ghi789jkl012",
    service: "order-service",
    operation: "GET /orders/:id",
    duration: 45,
    status: "ok",
  },
  {
    id: "trace-04",
    traceId: "ghi789jkl012",
    service: "order-service",
    operation: "SELECT orders",
    duration: 12,
    status: "ok",
  },
  {
    id: "trace-05",
    traceId: "mno345pqr678",
    service: "notification-service",
    operation: "POST /push/send",
    duration: 234,
    status: "ok",
  },
  {
    id: "trace-06",
    traceId: "mno345pqr678",
    service: "apns",
    operation: "APNs Push",
    duration: 180,
    status: "ok",
  },
  {
    id: "trace-07",
    traceId: "stu901vwx234",
    service: "payment-gateway",
    operation: "GET /health",
    duration: 3,
    status: "ok",
  },
  {
    id: "trace-08",
    traceId: "stu901vwx234",
    service: "order-service",
    operation: "POST /orders/batch",
    duration: 2800,
    status: "ok",
  },
];

// ── Alerts: Alert Rules (8 rules, 2 firing) ───────────────────────────

export const sampleAlertRules: AlertRule[] = [
  {
    id: "alert-01",
    name: "High Error Rate — Payment Gateway",
    description: "Payment gateway error rate exceeds 1% for 5 minutes",
    severity: "critical",
    state: "firing",
    expression: 'rate(http_requests_total{service="payment-gateway",status=~"5.."}[5m]) > 0.01',
    duration: "5m",
    labels: { service: "payment-gateway", team: "sre" },
    lastFired: "2026-05-10T14:32:00Z",
  },
  {
    id: "alert-02",
    name: "DB Connection Pool Saturation",
    description: "Order service DB connection pool exceeded 90%",
    severity: "critical",
    state: "firing",
    expression: 'db_connection_pool_usage{service="order-service"} > 0.9',
    duration: "2m",
    labels: { service: "order-service", team: "sre" },
    lastFired: "2026-05-10T14:31:58Z",
  },
  {
    id: "alert-03",
    name: "P99 Latency Spike",
    description: "P99 response time above 500ms for 10 minutes",
    severity: "warning",
    state: "pending",
    expression: "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[10m])) > 0.5",
    duration: "10m",
    labels: { service: "*", team: "sre" },
    lastFired: null,
  },
  {
    id: "alert-04",
    name: "Notification Queue Backlog",
    description: "Notification push queue depth exceeds 3000",
    severity: "warning",
    state: "inactive",
    expression: 'queue_depth{queue="notification-push"} > 3000',
    duration: "5m",
    labels: { service: "notification-service", team: "sre" },
    lastFired: "2026-05-10T12:00:00Z",
  },
  {
    id: "alert-05",
    name: "Kafka Consumer Lag",
    description: "Consumer group lag exceeds 10000 messages",
    severity: "warning",
    state: "inactive",
    expression: 'kafka_consumer_lag{group="order-processor"} > 10000',
    duration: "15m",
    labels: { service: "order-service", team: "sre" },
    lastFired: "2026-05-09T22:00:00Z",
  },
  {
    id: "alert-06",
    name: "Certificate Expiry",
    description: "TLS certificate expires in less than 7 days",
    severity: "critical",
    state: "inactive",
    expression: "cert_expiry_days < 7",
    duration: "1h",
    labels: { service: "payment-gateway", team: "security" },
    lastFired: null,
  },
  {
    id: "alert-07",
    name: "High CPU Usage",
    description: "CPU usage above 85% for 5 minutes",
    severity: "warning",
    state: "inactive",
    expression: 'avg(rate(node_cpu_seconds_total{mode="user"}[5m])) by (instance) > 0.85',
    duration: "5m",
    labels: { service: "*", team: "sre" },
    lastFired: "2026-05-09T15:30:00Z",
  },
  {
    id: "alert-08",
    name: "Disk Space Low",
    description: "Disk usage exceeds 90% on any production node",
    severity: "critical",
    state: "pending",
    expression: "disk_usage_percent > 90",
    duration: "1h",
    labels: { service: "*", team: "infra" },
    lastFired: null,
  },
];

// ── Incidents: 12 incidents (3 open) ──────────────────────────────────

export const sampleIncidents: Incident[] = [
  {
    id: "inc-01",
    title: "Payment gateway error rate spike",
    severity: "SEV0",
    status: "open",
    service: "payment-gateway",
    commander: "zhangsan",
    createdAt: "2026-05-10T14:32:00Z",
    updatedAt: "2026-05-10T14:32:00Z",
    summary: "Upstream payment processor timeout causing cascading failures. Rollback initiated.",
  },
  {
    id: "inc-02",
    title: "Order service DB connection pool exhausted",
    severity: "SEV1",
    status: "investigating",
    service: "order-service",
    commander: "lisi",
    createdAt: "2026-05-10T14:31:00Z",
    updatedAt: "2026-05-10T14:33:00Z",
    summary: "Connection pool maxed out at 120. Analyzing connection leak hypothesis.",
  },
  {
    id: "inc-03",
    title: "Notification push delay > 30s",
    severity: "SEV2",
    status: "open",
    service: "notification-service",
    commander: "wangwu",
    createdAt: "2026-05-10T14:30:00Z",
    updatedAt: "2026-05-10T14:31:00Z",
    summary: "APNs rate limiting causing push queue backlog. Investigating FCM failover.",
  },
  {
    id: "inc-04",
    title: "SSL certificate verification failure",
    severity: "SEV1",
    status: "mitigated",
    service: "payment-gateway",
    commander: "zhangsan",
    createdAt: "2026-05-10T13:00:00Z",
    updatedAt: "2026-05-10T13:45:00Z",
    summary: "Partner API SSL cert expired. Switched to backup endpoint.",
  },
  {
    id: "inc-05",
    title: "Kafka consumer group rebalance storm",
    severity: "SEV2",
    status: "resolved",
    service: "order-service",
    commander: "lisi",
    createdAt: "2026-05-09T18:00:00Z",
    updatedAt: "2026-05-09T19:30:00Z",
    summary: "Multiple rebalances triggered by frequent consumer restarts. Tuned heartbeat config.",
  },
  {
    id: "inc-06",
    title: "Redis cluster node failure",
    severity: "SEV1",
    status: "resolved",
    service: "payment-gateway",
    commander: "zhangsan",
    createdAt: "2026-05-09T10:00:00Z",
    updatedAt: "2026-05-09T11:20:00Z",
    summary: "Primary node OOM killed. Automatic failover to replica succeeded.",
  },
  {
    id: "inc-07",
    title: "FCM delivery rate degradation",
    severity: "SEV2",
    status: "resolved",
    service: "notification-service",
    commander: "wangwu",
    createdAt: "2026-05-08T16:00:00Z",
    updatedAt: "2026-05-08T18:00:00Z",
    summary: "FCM API throttling. Switched to APNs as primary channel temporarily.",
  },
  {
    id: "inc-08",
    title: "Database slow query spike",
    severity: "SEV2",
    status: "resolved",
    service: "order-service",
    commander: "lisi",
    createdAt: "2026-05-08T09:00:00Z",
    updatedAt: "2026-05-08T09:45:00Z",
    summary: "Missing index on status column. Added composite index.",
  },
  {
    id: "inc-09",
    title: "Load balancer unhealthy target",
    severity: "SEV2",
    status: "resolved",
    service: "payment-gateway",
    commander: "zhangsan",
    createdAt: "2026-05-07T14:00:00Z",
    updatedAt: "2026-05-07T14:30:00Z",
    summary: "One instance failing health check. Replaced instance.",
  },
  {
    id: "inc-10",
    title: "Metrics pipeline data gap",
    severity: "SEV3",
    status: "resolved",
    service: "notification-service",
    commander: "wangwu",
    createdAt: "2026-05-07T08:00:00Z",
    updatedAt: "2026-05-07T10:00:00Z",
    summary: "Prometheus remote write failing. Restarted Thanos sidecar.",
  },
  {
    id: "inc-11",
    title: "Circuit breaker opened on payment processor",
    severity: "SEV0",
    status: "resolved",
    service: "payment-gateway",
    commander: "zhangsan",
    createdAt: "2026-05-06T20:00:00Z",
    updatedAt: "2026-05-06T22:15:00Z",
    summary: "Third-party processor timeout. Manual reset after processor recovered.",
  },
  {
    id: "inc-12",
    title: "Deploy rollback triggered",
    severity: "SEV1",
    status: "resolved",
    service: "order-service",
    commander: "lisi",
    createdAt: "2026-05-06T15:00:00Z",
    updatedAt: "2026-05-06T15:20:00Z",
    summary: "New version caused memory leak. Rolled back to v2.8.4.",
  },
];

// ── Rollbacks: 4 records ──────────────────────────────────────────────

export const sampleRollbacks: RollbackRecord[] = [
  {
    id: "rbk-01",
    service: "order-service",
    versionFrom: "v2.8.5",
    versionTo: "v2.8.4",
    trigger: "auto",
    result: "success",
    reason: "Canary P99 latency exceeded threshold by 3x within 2 minutes of deploy",
    duration: 45,
    operator: "auto",
    createdAt: "2026-05-10T13:15:00Z",
  },
  {
    id: "rbk-02",
    service: "payment-gateway",
    versionFrom: "v3.1.2",
    versionTo: "v3.1.1",
    trigger: "manual",
    result: "success",
    reason: "SEV0 incident: upstream processor timeout under new TLS config",
    duration: 28,
    operator: "zhangsan",
    createdAt: "2026-05-10T14:32:30Z",
  },
  {
    id: "rbk-03",
    service: "notification-service",
    versionFrom: "v1.5.0",
    versionTo: "v1.4.9",
    trigger: "auto",
    result: "success",
    reason: "Push delivery rate dropped below 95% SLA after deploy",
    duration: 52,
    operator: "auto",
    createdAt: "2026-05-09T11:30:00Z",
  },
  {
    id: "rbk-04",
    service: "payment-gateway",
    versionFrom: "v3.1.0",
    versionTo: "v3.0.9",
    trigger: "manual",
    result: "failed",
    reason:
      "Manual rollback attempted after Redis connection drop — schema mismatch blocked rollback",
    duration: 120,
    operator: "zhangsan",
    createdAt: "2026-05-08T17:00:00Z",
  },
];
